describe("Pruebas en automationexercise", () => {
    it('Registrar usuario', () => {
cy.visit('https://automationexercise.com/')
cy.get('section[style="height: auto !important;"] > .container > .row')
cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
cy.get('[data-qa="signup-name"]').type('Oso')
cy.get('[data-qa="signup-email"]').type('oemy19@xmail.com')
cy.get('[data-qa="signup-button"]').click()
cy.get('[data-qa="password"]').type('Mimu2377')
cy.get('[data-qa="days"]').select('3')
cy.get('[data-qa="months"]').select('April')
cy.get('[data-qa="years"]').select('1974')
cy.get('#id_gender1').click()
cy.get('[data-qa="first_name"]').type('Jose Oso')
cy.get('[data-qa="last_name"]').type('Muñoz')
cy.get('[data-qa="company"]').type('OsoLogistics')
cy.get('[data-qa="address"]').type('Ramón Llull')
cy.get('[data-qa="country"]').select('United States')
cy.get('[data-qa="state"]').type('New York')
cy.get('[data-qa="city"]').type('Manhattan')
cy.get('[data-qa="zipcode"]').type('08780')
cy.get('[data-qa="mobile_number"]').type('627986532')
cy.get('[data-qa="create-account"]').click()
cy.get('[data-qa="continue-button"]').click()
cy.get(':nth-child(10) > a').should('be.visible')
cy.get('.shop-menu > .nav > :nth-child(5) > a').click()
cy.get('b').should('be.visible')
cy.get('[data-qa="continue-button"]').click()

 })

 it('Login usuario', () => {
    cy.visit('https://automationexercise.com/')
    cy.get('section[style="height: auto !important;"] > .container > .row').should('be.visible')
    cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
    cy.get('.login-form > h2').should('be.visible')
    cy.get('[data-qa="login-email"]').type('oemy19@hotmail.com')
    cy.get('[data-qa="login-password"]').type('Mimu2377')
    cy.get('[data-qa="login-button"]').click()
    cy.get(':nth-child(10) > a').should('be.visible')
    cy.get('.shop-menu > .nav > :nth-child(5) > a').click()
    cy.get('b').should('be.visible')

 })


    it('Registrar usuario', () => {
    cy.visit('https://automationexercise.com/')
    cy.get('section[style="height: auto !important;"] > .container > .row')
    cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
    cy.get('[data-qa="signup-name"]').type('Manuelgonzalez')
    cy.get('[data-qa="signup-email"]').type('pericodelospalotess@gmail.com')
    cy.get('[data-qa="signup-button"]').click()
    cy.get('[data-qa="password"]').type('raul123')
    cy.get('[data-qa="days"]').select('5')
    cy.get('[data-qa="months"]').select('August')
    cy.get('[data-qa="years"]').select('1995')
    cy.get('#id_gender1').click()
    cy.get('[data-qa="first_name"]').type('benalmadena')
    cy.get('[data-qa="last_name"]').type('Málaga')
    cy.get('[data-qa="country"]').select('United States')
    cy.get('[data-qa="state"]').type('Washington')
    cy.get('[data-qa="city"]').type('Washington')
    cy.get('[data-qa="zipcode"]').type('1234')
    cy.get('[data-qa="mobile_number"]').type('123456789')
    cy.get('[data-qa="address"]').type('dirección de prueba')
    cy.get('[data-qa="create-account"]').click()
    cy.get('[data-qa="continue-button"]').click()
    cy.get(':nth-child(10) > a').should('be.visible')
    cy.get('.shop-menu > .nav > :nth-child(5) > a').click()
    cy.get('b').should('be.visible')
    cy.get('[data-qa="continue-button"]').click()
    })
   
    it.only('Login con usuario y contraseña correcto', () => {
       cy.visit('https://automationexercise.com/')
       cy.get('section[style="height: auto !important;"] > .container > .row').should('be.visible')
       cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
       cy.get('.login-form > h2').should('be.visible')
       cy.get('[data-qa="login-email"]').type('emaildeprueba555@gmail.com')
       cy.get('[data-qa="login-password"]').type('1234')
       cy.get('[data-qa="login-button"]').click()
       cy.get(':nth-child(10) > a').should('be.visible')
       cy.get('.shop-menu > .nav > :nth-child(5) > a').click()
       cy.get('.shop-menu > .nav > :nth-child(5) > a').should('be.visible')
   
   })
})